//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSDUas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habit
    {
        public System.Guid Id { get; set; }
        public string name { get; set; }
        public string days_off { get; set; }
        public Nullable<int> current_streak { get; set; }
        public Nullable<int> longest_streak { get; set; }
        public Nullable<int> log_count { get; set; }
        public string logs { get; set; }
        public System.Guid user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
